### ISSUE TITLE
Proposal: Make External Plugins Update Automatically

### ISSUE THREAD

**Issue by captncraig** [caddyserver/buildsrv#15]
Currently @mholt updates plugins on the build server by hand. This "works", but it requires a bit of timing and communication, as well as a manual process, which I dislike. It would be nice if plugin authors could control which version of their plugin gets deployed. As noted in the code, simply deploying master is asking for instability.
### Problems / Goals
- Package author should be able to trigger an update to a specific version/commit of their plugin.
- Binary from the download page should update accordingly.
### Implementation

My first idea was some kind of web ui with some credential system and a field for authors to specify a commit to use. That seems like it would be cool, but also sounds hard to get right. 

I realized we already have a lot of this logic in the git plugin. Assuming buildsrv is running behind caddy, it may be as simple as adding to the caddyfile some git directives:

```
http://127.0.0.1:11111 { #server doesn't actually matter
   root /gopath/src

  git https://gihub.com/author/repo.git githib.com/author/repo {
      branch buildsrv
      then /scripts/invalidateCache.sh #not sure exactly what is involved here
  }

  git https://gihub.com/author/repo2.git githib.com/author/repo2 {
      branch buildsrv
  }
}
```

This way the checked out copy on the build server will always track the `buildsrv` branch (or tag maybe depending on if the git plugin supports it).

A few potential Issues:
1. This creates a new contract for plugin maintainers. The `buildsrv` branch must always be stable with the current release version of caddy. Not a huge bar, but it does require trusting people a little more. Perhaps new plugin authors would need to have a caddy maintainer manually update their plugins through a grace period.
2. No validation. It could be made a bit more stable by checking out to a second gopath, validating the compile, and then copying it to the real gopath for the build server. `then` could coordinate all of that with the right scripts so that a bad update never creates a failed build.

**Comment by mholt** [comment]
Related to stable builds: I've drafted up a quick stream-of-consciousness that describes how the new build server will work: https://gist.github.com/mholt/f871bdee3f35f2f7c6ab - basically, each "version" is its own GOPATH, and before rotating to a new GOPATH it does a series of tests and builds to ensure the new "version" works. If so, it completes the rotation; if not, it rolls back and reports an error.

But I'm glad you're thinking about how to trigger a rotation, since that's still kind of up in the air.

**Comment by captncraig** [comment]
Wow, I hadn't seen that before. I do like that the entire build environment is essentially frozen for each version of everything. I would worry about proliferation of copies of files, with each "gopath" being essentially identical for the majority of files.

It is also a fairly major overhaul. My way can be dropped in one plugin at a time and hopefully not break anything.

**Comment by mholt** [comment]
@captncraig As we prepare to write a new build server (probably _after_ the 0.9 release sometime), we should revisit these proposals.

**Comment by mholt** [comment]
New build server implemented -- hope you'll try it. :)
