### ISSUE TITLE
Proposal: Sync docs from actual plugin repo

### ISSUE THREAD

**Issue by captncraig** [caddyserver/buildsrv#16]
This is an additional possibility that comes as an expansion on #15. If #15 is rejected this may be a bit trickier.

There are a few problems with the current way docs are managed for caddyserver.com:
1. A plugin author must make separate commits for docs and features to two different repos.
2. If a plugin makes large changes, docs must be pushed at the same time as the new version is pushed to the build server.
3. Because of 1, feature changes often go undocumented.

I have found that it is extremely nice to have docs in the same repo as the code. It allows you to require PRs to document their changes before merging, and it ensures that docs and code always match for a given commit.

I propose that:
1. Package authors keep the documentation html or markdown in their own repo. It should be in the same format it is now, able to be included in caddyserver.com.
2. When a new version of the plugin is downloaded to the build server (via caddy git plugin), we run an additional script which syncs the file to the caddyserver.com repo (via PR or direct push to master).

Could be as simple as `then go run /scripts/copyDocs.go docs.md /public/docs/myPlugin.md` 

The script would use github's api to update the file directly.

**Comment by mholt** [comment]
With the new build server, docs will be hosted off-site at the plugin owner's site or repo. But the description and some examples will still be hosted at the Caddy website, which are updatable by logging in. I think it's a good balance of easy implementation and what you're looking for here.

Incidentally, this is API-accessible too. I'll document that later. Thanks!
