### ISSUE TITLE
Unable to build caddy with git addon for linux amd64

### ISSUE THREAD

**Issue by tarfu** [caddyserver/buildsrv#2]
Hi,

I'm unable to get a version of caddy 0.7.2 with the git addon.
Building it for linux x86 and a lot of other ones are working.
Linux amd64 without git is working as well.

To state it clear I report this for the caddy download page on the website

Regards,

Tobias

**Comment by abiosoft** [comment]
Hi, are there any particular error message you're getting ?

Also, we're you trying to target linux amd64 from another platform or you're building from linux amd64?

**Comment by mholt** [comment]
Thanks for the report. I was able to reproduce this, but when I restarted the build server to examine it in more detail, the error went away and it started working. I will keep looking into this...

**Comment by mholt** [comment]
Oh yeah. I think this was fixed a while ago with ac936153590cdb0619b0b058cfb22ce280ac5215. It was caused as a result of a failed build not being cleaned up - but the build server still thought it was 'in progress'. Should be taken care of now.
