### ISSUE TITLE
Can't do two builds at a time

### ISSUE THREAD

**Issue by mholt** [caddyserver/buildsrv#3]
Running two builds at a time doesn't work (I had the git feature selected for both). The second one shows a 500 Internal Server Error. This error is in the logs:

2015/07/02 21:34:31 [500 /download/build?os=freebsd&arch=386&features=git] Directive 'git' exists in Caddy core, use a distinct name.

@abiosoft Is this because it's copying the code to the same place or something? I probably introduced the bug, but you're familiar with the code gen part, so I wanted your opinion as to what might be causing it.

**Comment by abiosoft** [comment]
I'll have a look.

**Comment by mholt** [comment]
Thanks for your PR. So what I understand from it is that the second build was sharing a GOPATH with the first build, which already spliced in the git directive. So when the second build loaded that source file, it already found the git directive there, causing the error. To fix it, the PR uses a separate GOPATH for every build and associates that path with the build struct to avoid collisions. Am I close?

**Comment by abiosoft** [comment]
Yeah. Exactly. :+1:
