### ISSUE TITLE
Change in plugin policy: Build latest signed tag(s) of plugins.

### ISSUE THREAD

**Issue by wmark** [caddyserver/buildsrv#36]
This is due to wmark/caddy.upload#15.

The official current policy ([3rd revision](https://github.com/mholt/caddy/wiki/Publishing-a-Plugin-to-the-Download-Page#3-register-plugin)) is, with sporadic updates adding to precedence:

> You may continue pushing to master on your repository without breaking the build server, as it only updates when you tell us to update it. Make sure not to forget that!

I propose a change to this policy, which then will be as follows:

> You may continue pushing to master on your repository and it will not break the build server.
> Updates to plugins to be picked up are signalled by tagging the corresponding commit in branch _master_ (or whatever default branch you have set).
> Those tags need to be signed by you.
- This enables to have updates to plugins in a well-defined and controllable manner.
- This helps in debugging of issues reported to plugin authors: We don't need to guess which commit has been used by the _buildsrv_.
- Caddy's sole maintainer, @mholt, does not need to be contacted on every update. Updates can be automated using a cronjob or _systemd timers_ or the like safely.
- Signed tags (think: by one agreed-upon key/id/email address) prevent new releases being pulled in by accident, that is if a collaborator signed one.

This is easy to operationalize in practice, for example you can detect if any new tags appeared in the repository of plugin **upload** like this, without diluting _Github's_ stats regarding visitors and _git clones_:

``` bash
curl --silent --show-error --fail --location --header 'Accept: application/json' \
  https://api.github.com/repos/wmark/caddy.upload/tags \
| jq -r '.[0] | .name' \
> .last
```

… then – in a cronjob – just compare:

``` bash
: ${PLUGIN:="upload"}
if [[ "$(git log --pretty=oneline | cut -d ' ' -f 1 | head -n 1)" != "$(above call)" ]]; then
  if ! git pull; then
    cd ..
    rm -rf $PLUGIN
    git clone https://…/$PLUGIN
    cd $PLUGIN
  fi

  while read TAG; do
    git checkout $TAG
    … check signature && break
  done < <(… list all tags in HEAD desc)
fi
```

… whereas the signature checking could be postponed to allow plugin maintainers to get familiar with signing of tags.

**Comment by mholt** [comment]
Hey Mark, great idea! :smile: I'm already working on this with a new build server, so that nearly everything about plugin development and deployment can be automated, because you're right: I definitely do not care to manually do all of this much longer.

So, I realize that your plugin is ready to update -- I'll get it updated as soon as I can... maybe ping me again in a week if I haven't gotten to it.

**Comment by wendigo** [comment]
@mholt did you thought about using incoming go1.8 -buildmode=plugin ?

**Comment by mholt** [comment]
@wendigo Yes, I'm looking at it. See https://forum.caddyserver.com/t/go-1-8-plugin-model/934?u=matt

**Comment by mholt** [comment]
New build server basically implements this. Thanks!
